language: python
sudo: false

python:
  - "3.6"
install:
  - python -m pip install .
  - python -m pip install -r dev_requirements.txt
script:
  - pytest --cov=aiograph tests/

branches:
  only:
  - master

after_success:
  - codecov