sudo: false

language: python
python:
  - "3.6"
  - "3.7"

install:
  - python -m pip install .
  - python -m pip install -r dev_requirements.txt
script:
  - pytest --cov=aiograph tests/
after_success:
  - codecov
